cs_dust.wad
gfx/env/badlandsup.tga
gfx/env/badlandsbk.tga
gfx/env/badlandsdn.tga
gfx/env/badlandsft.tga
gfx/env/badlandslf.tga
gfx/env/badlandsrt.tga
sprites/wsplash3.spr
sound/ambience/waterfall3.wav
models/gozm.mdl
