chateau.wad
itsitaly.wad
maps/zm_flood_detail.txt
gfx/detail/dt_brick.tga
gfx/detail/dt_wood2.tga
gfx/detail/dt_wood.tga
gfx/detail/dt_stone1.tga
gfx/detail/dt_leather1.tga
gfx/detail/dt_grass1.tga
gfx/detail/dt_carpet1.tga
gfx/detail/dt_ground1.tga
gfx/detail/dt_plaster2.tga
gfx/detail/dt_smooth1.tga
gfx/detail/dt_fabric2.tga
gfx/detail/dt_rock1.tga
gfx/env/grnplsntup.tga
gfx/env/grnplsntdn.tga
gfx/env/grnplsntlf.tga
gfx/env/grnplsntrt.tga
gfx/env/grnplsntft.tga
gfx/env/grnplsntbk.tga
