ALTER TABLE  `superban` ENGINE = INNODB DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;
ALTER TABLE  `superban` CHANGE  `time`  `time` INT NOT NULL ;
ALTER TABLE  `superban` CHANGE  `bantime`  `bantime` INT NOT NULL ;
ALTER TABLE  `superban` CHANGE  `unbantime`  `unbantime` INT NOT NULL ;
ALTER TABLE  `superban` CHANGE  `ip`  `ip` VARCHAR( 64 ) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT  '';
ALTER TABLE  `superban` CHANGE  `ipcookie`  `ipcookie` VARCHAR( 64 ) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT  '';
ALTER TABLE  `superban` CHANGE  `uid`  `uid` VARCHAR( 64 ) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT  '';
ALTER TABLE  `superban` CHANGE  `banname`  `banname` VARCHAR( 64 ) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT  '';
ALTER TABLE  `superban` CHANGE  `name`  `name` VARCHAR( 64 ) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT  '';
ALTER TABLE  `superban` CHANGE  `admin`  `admin` VARCHAR( 64 ) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT  '';
ALTER TABLE  `superban` CHANGE  `reason`  `reason` VARCHAR( 255 ) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT  '';
ALTER TABLE  `superban` ADD  `sid` VARCHAR( 64 ) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT  '' AFTER  `banid` ;
ALTER TABLE  `superban` ADD INDEX  `sid` (  `sid` ) COMMENT  '';
ALTER TABLE  `superban` ADD INDEX  `ip` (  `ip` ) COMMENT  '';
ALTER TABLE  `superban` ADD INDEX  `ipcookie` (  `ipcookie` ) COMMENT  '';
ALTER TABLE  `superban` ADD INDEX  `uid` (  `uid` ) COMMENT  '';
ALTER TABLE  `superban` ADD INDEX  `banname` (  `banname` ) COMMENT  '';
ALTER TABLE  `superban` ADD INDEX  `name` (  `name` ) COMMENT  '';
ALTER TABLE  `superban` ADD INDEX  `unbantime` (  `unbantime` ) COMMENT  '';